# Generated by Django 3.0.5 on 2020-05-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100)),
                ('dividend', models.FloatField(verbose_name=2)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField(verbose_name=2)),
                ('shares_needed', models.IntegerField(verbose_name=0)),
                ('investment_needed', models.IntegerField(verbose_name=0)),
            ],
        ),
    ]
