# Generated by Django 3.0.6 on 2020-05-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0002_stock_ticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='investment_needed',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='shares_needed',
        ),
    ]
