# Generated by Django 3.0.6 on 2020-05-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0004_stock_is_investable'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsupportedStocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=4)),
            ],
        ),
    ]
