# Generated by Django 3.0.6 on 2020-05-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0005_unsupportedstocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_owned',
            field=models.BooleanField(default=False),
        ),
    ]
