# Generated by Django 3.0.6 on 2020-05-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0006_stock_is_owned'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='ex_div_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
