# Generated by Django 3.0.6 on 2020-05-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0008_auto_20200516_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ex_div_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
