# Generated by Django 3.0.6 on 2020-05-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0009_auto_20200517_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='is_owned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
