# Generated by Django 3.0.6 on 2020-05-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0010_auto_20200518_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='next_div_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='shares_owned',
            field=models.IntegerField(default=0),
        ),
    ]
