# Generated by Django 3.0.6 on 2020-05-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0012_auto_20200527_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unsupportedstocks',
            name='ticker',
            field=models.CharField(max_length=5),
        ),
    ]
