# Generated by Django 3.0.6 on 2020-06-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0013_auto_20200529_0156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnsupportedStocks',
        ),
        migrations.AlterField(
            model_name='stock',
            name='dividend',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.FloatField(),
        ),
    ]
